#!/usr/bin/env python3
"""
Generate src/chr.c (8 KiB CHR-ROM) and src/gen_title.h (logo tile map).

BG bank (256 tiles): 0x00-0x7F font (tile == ASCII), 0x80-0x82 blocks/shades,
0x83.. unique logo tiles. Black logo cells reuse blank 0x00, white cells the
solid block 0x80, keeping the logo within the free slots.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_H = ROOT / "tools" / "font8x8_basic.h"
LOGO = ROOT / "references" / "hashcatlogo.png"
OUT_CHR = ROOT / "src" / "chr.c"
OUT_TITLE = ROOT / "src" / "gen_title.h"

TILE_SOLID = 0x80
TILE_SHADE = 0x81
TILE_LIGHT = 0x82
LOGO_BASE = 0x83          # first tile index available to the logo
LOGO_MAX = 0xFF           # last usable tile in the bank

# Logo target grid (tiles). 32x8 == full width, 64px tall.
LOGO_TW = 32
LOGO_TH = 8
LOGO_THRESH = 110


def parse_font(path):
    body = path.read_text()
    body = body[body.index("{"):]
    b = [int(h, 16) for h in re.findall(r"0x[0-9A-Fa-f]{2}", body)]
    if len(b) < 128 * 8:
        sys.exit("font parse failed")
    return [b[i * 8:(i + 1) * 8] for i in range(128)]


def revbits(b):
    b = ((b & 0xF0) >> 4) | ((b & 0x0F) << 4)
    b = ((b & 0xCC) >> 2) | ((b & 0x33) << 2)
    b = ((b & 0xAA) >> 1) | ((b & 0x55) << 1)
    return b & 0xFF


def font_tile(rows):
    return [revbits(r & 0xFF) for r in rows] + [0] * 8


def solid_tile():
    return [0xFF] * 8 + [0] * 8


def shade_tile():
    return [0xAA, 0x55] * 4 + [0] * 8


def light_tile():
    return [0x88, 0x00, 0x22, 0x00] * 2 + [0] * 8


def load_logo_bits():
    """Return a LOGO_TH*8 x LOGO_TW*8 grid of 0/1, or None if unavailable."""
    try:
        from PIL import Image
    except ImportError:
        return None
    if not LOGO.exists():
        return None
    im = Image.open(LOGO).convert("RGBA")
    px = im.load()
    W, H = im.size

    def on(x, y):
        r, g, b, a = px[x, y]
        return a > 128 and (r + g + b) > 3 * 180  # bright + opaque = wordmark

    xs, ys = [], []
    for y in range(H):
        for x in range(W):
            if on(x, y):
                xs.append(x)
                ys.append(y)
    if not xs:
        return None
    crop = im.crop((min(xs), min(ys), max(xs) + 1, max(ys) + 1))
    g = crop.resize((LOGO_TW * 8, LOGO_TH * 8), Image.LANCZOS).convert("L")
    gp = g.load()
    return [[1 if gp[x, y] > LOGO_THRESH else 0 for x in range(LOGO_TW * 8)]
            for y in range(LOGO_TH * 8)]


def bits_to_tile(bits, tx, ty):
    """8x8 cell -> (16 CHR bytes plane0+plane1, key)."""
    plane0 = []
    for row in range(8):
        byte = 0
        for col in range(8):
            if bits[ty * 8 + row][tx * 8 + col]:
                byte |= 0x80 >> col
        plane0.append(byte)
    key = tuple(plane0)
    return plane0 + [0] * 8, key


def main():
    glyphs = parse_font(FONT_H)
    tiles = [font_tile(glyphs[i]) if i < 128 else [0] * 16 for i in range(256)]
    tiles[TILE_SOLID] = solid_tile()
    tiles[TILE_SHADE] = shade_tile()
    tiles[TILE_LIGHT] = light_tile()

    bits = load_logo_bits()
    logo_map = None
    if bits is not None:
        blank_key = tuple([0] * 8)
        solid_key = tuple([0xFF] * 8)
        pool = {blank_key: 0x00, solid_key: TILE_SOLID}
        nxt = LOGO_BASE
        logo_map = []
        for ty in range(LOGO_TH):
            for tx in range(LOGO_TW):
                data, key = bits_to_tile(bits, tx, ty)
                if key in pool:
                    idx = pool[key]
                else:
                    if nxt > LOGO_MAX:
                        sys.exit(f"logo needs >{LOGO_MAX - LOGO_BASE + 1} tiles")
                    idx = nxt
                    pool[key] = idx
                    tiles[idx] = data
                    nxt += 1
                logo_map.append(idx)
        print(f"logo: {nxt - LOGO_BASE} unique tiles (0x83..0x{nxt-1:02x})")

    # table0 = the 256 tiles above; table1 left blank (sprites unused).
    chr_rom = []
    for t in tiles:
        chr_rom.extend(t)
    chr_rom.extend([0] * 4096)

    with OUT_CHR.open("w") as f:
        f.write("// GENERATED by tools/gen_chr.py -- do not edit.\n")
        f.write("__attribute__((section(\".chr_rom\"), used))\n")
        f.write("const unsigned char chr_rom[8192] = {\n")
        for i in range(0, len(chr_rom), 16):
            f.write("  " + ",".join(f"0x{b:02x}" for b in chr_rom[i:i+16]) + ",\n")
        f.write("};\n")
    print(f"wrote {OUT_CHR}")

    with OUT_TITLE.open("w") as f:
        f.write("// GENERATED by tools/gen_chr.py -- hashcat wordmark tile map.\n")
        f.write("#ifndef HASHCAT_NES_GEN_TITLE_H\n#define HASHCAT_NES_GEN_TITLE_H\n\n")
        if logo_map is None:
            f.write("#define LOGO_OK 0\n")
        else:
            f.write("#define LOGO_OK 1\n")
            f.write(f"#define LOGO_W {LOGO_TW}\n#define LOGO_H {LOGO_TH}\n")
            f.write("static const unsigned char logo_map[LOGO_W * LOGO_H] = {\n")
            for ty in range(LOGO_TH):
                row = logo_map[ty*LOGO_TW:(ty+1)*LOGO_TW]
                f.write("  " + ",".join(f"0x{v:02x}" for v in row) + ",\n")
            f.write("};\n")
        f.write("\n#endif\n")
    print(f"wrote {OUT_TITLE}")


if __name__ == "__main__":
    main()
